name: dbt_airline
version: '1.0.0'
config-version: 2
profile: dbt_airline

model-paths: ['models']
target-path: 'target'
clean-targets: ['target', 'dbt_packages']

models:
  dbt_airline:
    staging:
      +materialized: view
      +schema: caso6_db
    intermediate:
      +materialized: table
      +schema: caso6_db
    marts:
      +materialized: table
      +schema: caso6_db
      +s3_data_dir: s3://caso6-curated/
      +s3_tmp_table_dir: s3://caso6-curated/tmp/
